// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: nexus/metadata/v1/metadata.proto

package metadatav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColumnType int32

const (
	ColumnType_COLUMN_TYPE_UNSPECIFIED ColumnType = 0
	ColumnType_COLUMN_TYPE_INT8        ColumnType = 1
	ColumnType_COLUMN_TYPE_INT16       ColumnType = 2
	ColumnType_COLUMN_TYPE_INT32       ColumnType = 3
	ColumnType_COLUMN_TYPE_INT64       ColumnType = 4
	ColumnType_COLUMN_TYPE_UINT8       ColumnType = 5
	ColumnType_COLUMN_TYPE_UINT16      ColumnType = 6
	ColumnType_COLUMN_TYPE_UINT32      ColumnType = 7
	ColumnType_COLUMN_TYPE_UINT64      ColumnType = 8
	ColumnType_COLUMN_TYPE_STRING      ColumnType = 9
	ColumnType_COLUMN_TYPE_BOOLEAN     ColumnType = 10
	ColumnType_COLUMN_TYPE_TIMESTAMP   ColumnType = 11
	ColumnType_COLUMN_TYPE_BYTES       ColumnType = 12
)

// Enum value maps for ColumnType.
var (
	ColumnType_name = map[int32]string{
		0:  "COLUMN_TYPE_UNSPECIFIED",
		1:  "COLUMN_TYPE_INT8",
		2:  "COLUMN_TYPE_INT16",
		3:  "COLUMN_TYPE_INT32",
		4:  "COLUMN_TYPE_INT64",
		5:  "COLUMN_TYPE_UINT8",
		6:  "COLUMN_TYPE_UINT16",
		7:  "COLUMN_TYPE_UINT32",
		8:  "COLUMN_TYPE_UINT64",
		9:  "COLUMN_TYPE_STRING",
		10: "COLUMN_TYPE_BOOLEAN",
		11: "COLUMN_TYPE_TIMESTAMP",
		12: "COLUMN_TYPE_BYTES",
	}
	ColumnType_value = map[string]int32{
		"COLUMN_TYPE_UNSPECIFIED": 0,
		"COLUMN_TYPE_INT8":        1,
		"COLUMN_TYPE_INT16":       2,
		"COLUMN_TYPE_INT32":       3,
		"COLUMN_TYPE_INT64":       4,
		"COLUMN_TYPE_UINT8":       5,
		"COLUMN_TYPE_UINT16":      6,
		"COLUMN_TYPE_UINT32":      7,
		"COLUMN_TYPE_UINT64":      8,
		"COLUMN_TYPE_STRING":      9,
		"COLUMN_TYPE_BOOLEAN":     10,
		"COLUMN_TYPE_TIMESTAMP":   11,
		"COLUMN_TYPE_BYTES":       12,
	}
)

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}

func (x ColumnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnType) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_metadata_v1_metadata_proto_enumTypes[0].Descriptor()
}

func (ColumnType) Type() protoreflect.EnumType {
	return &file_nexus_metadata_v1_metadata_proto_enumTypes[0]
}

func (x ColumnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnType.Descriptor instead.
func (ColumnType) EnumDescriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{0}
}

type CompactionLevel int32

const (
	CompactionLevel_COMPACTION_LEVEL_UNSPECIFIED CompactionLevel = 0
	CompactionLevel_COMPACTION_LEVEL_ZERO        CompactionLevel = 1
	CompactionLevel_COMPACTION_LEVEL_ONE         CompactionLevel = 2
)

// Enum value maps for CompactionLevel.
var (
	CompactionLevel_name = map[int32]string{
		0: "COMPACTION_LEVEL_UNSPECIFIED",
		1: "COMPACTION_LEVEL_ZERO",
		2: "COMPACTION_LEVEL_ONE",
	}
	CompactionLevel_value = map[string]int32{
		"COMPACTION_LEVEL_UNSPECIFIED": 0,
		"COMPACTION_LEVEL_ZERO":        1,
		"COMPACTION_LEVEL_ONE":         2,
	}
)

func (x CompactionLevel) Enum() *CompactionLevel {
	p := new(CompactionLevel)
	*p = x
	return p
}

func (x CompactionLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompactionLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_metadata_v1_metadata_proto_enumTypes[1].Descriptor()
}

func (CompactionLevel) Type() protoreflect.EnumType {
	return &file_nexus_metadata_v1_metadata_proto_enumTypes[1]
}

func (x CompactionLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompactionLevel.Descriptor instead.
func (CompactionLevel) EnumDescriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{1}
}

type Compression int32

const (
	Compression_COMPRESSION_UNSPECIFIED Compression = 0
	Compression_COMPRESSION_ZSTD        Compression = 1
	Compression_COMPRESSION_LZ4         Compression = 2
	Compression_COMPRESSION_SNAPPY      Compression = 3
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_UNSPECIFIED",
		1: "COMPRESSION_ZSTD",
		2: "COMPRESSION_LZ4",
		3: "COMPRESSION_SNAPPY",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_UNSPECIFIED": 0,
		"COMPRESSION_ZSTD":        1,
		"COMPRESSION_LZ4":         2,
		"COMPRESSION_SNAPPY":      3,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_metadata_v1_metadata_proto_enumTypes[2].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_nexus_metadata_v1_metadata_proto_enumTypes[2]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{2}
}

type CreateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationResponse) Reset() {
	*x = CreateOrganizationResponse{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationResponse) ProtoMessage() {}

func (x *CreateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrganizationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrganizationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeleteOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationRequest) Reset() {
	*x = DeleteOrganizationRequest{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationRequest) ProtoMessage() {}

func (x *DeleteOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationResponse) Reset() {
	*x = DeleteOrganizationResponse{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationResponse) ProtoMessage() {}

func (x *DeleteOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteOrganizationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteOrganizationResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreateTeamRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTeamRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type CreateTeamResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTeamResponse) Reset() {
	*x = CreateTeamResponse{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamResponse) ProtoMessage() {}

func (x *CreateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTeamResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTeamResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateTeamResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeleteTeamRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteTeamRequest) Reset() {
	*x = DeleteTeamRequest{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequest) ProtoMessage() {}

func (x *DeleteTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamRequest) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteTeamRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type DeleteTeamResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteTeamResponse) Reset() {
	*x = DeleteTeamResponse{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamResponse) ProtoMessage() {}

func (x *DeleteTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamResponse) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTeamResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteTeamResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DeleteTeamResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreatePartitionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId    string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TeamId            string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ClusterId         string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Id                string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	PartitionMetadata *PartitionMetadata     `protobuf:"bytes,5,opt,name=partition_metadata,json=partitionMetadata,proto3" json:"partition_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePartitionRequest) Reset() {
	*x = CreatePartitionRequest{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartitionRequest) ProtoMessage() {}

func (x *CreatePartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartitionRequest.ProtoReflect.Descriptor instead.
func (*CreatePartitionRequest) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePartitionRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreatePartitionRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreatePartitionRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *CreatePartitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePartitionRequest) GetPartitionMetadata() *PartitionMetadata {
	if x != nil {
		return x.PartitionMetadata
	}
	return nil
}

type CreatePartitionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId    string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TeamId            string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ClusterId         string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Id                string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	PartitionMetadata *PartitionMetadata     `protobuf:"bytes,5,opt,name=partition_metadata,json=partitionMetadata,proto3" json:"partition_metadata,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePartitionResponse) Reset() {
	*x = CreatePartitionResponse{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartitionResponse) ProtoMessage() {}

func (x *CreatePartitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartitionResponse.ProtoReflect.Descriptor instead.
func (*CreatePartitionResponse) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePartitionResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreatePartitionResponse) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreatePartitionResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *CreatePartitionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePartitionResponse) GetPartitionMetadata() *PartitionMetadata {
	if x != nil {
		return x.PartitionMetadata
	}
	return nil
}

func (x *CreatePartitionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListPartitionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TeamId         string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ClusterId      string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPartitionsRequest) Reset() {
	*x = ListPartitionsRequest{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsRequest) ProtoMessage() {}

func (x *ListPartitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsRequest.ProtoReflect.Descriptor instead.
func (*ListPartitionsRequest) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{10}
}

func (x *ListPartitionsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListPartitionsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListPartitionsRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ListPartitionsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListPartitionsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type ListPartitionsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId    string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TeamId            string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ClusterId         string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	StartTime         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	PartitionMetadata []*PartitionMetadata   `protobuf:"bytes,6,rep,name=partition_metadata,json=partitionMetadata,proto3" json:"partition_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListPartitionsResponse) Reset() {
	*x = ListPartitionsResponse{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsResponse) ProtoMessage() {}

func (x *ListPartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsResponse.ProtoReflect.Descriptor instead.
func (*ListPartitionsResponse) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{11}
}

func (x *ListPartitionsResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListPartitionsResponse) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListPartitionsResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ListPartitionsResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListPartitionsResponse) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListPartitionsResponse) GetPartitionMetadata() []*PartitionMetadata {
	if x != nil {
		return x.PartitionMetadata
	}
	return nil
}

type GetMetadataVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowSize    uint32                 `protobuf:"varint,1,opt,name=window_size,json=windowSize,proto3" json:"window_size,omitempty"`
	Window        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataVersionRequest) Reset() {
	*x = GetMetadataVersionRequest{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataVersionRequest) ProtoMessage() {}

func (x *GetMetadataVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataVersionRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataVersionRequest) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{12}
}

func (x *GetMetadataVersionRequest) GetWindowSize() uint32 {
	if x != nil {
		return x.WindowSize
	}
	return 0
}

func (x *GetMetadataVersionRequest) GetWindow() *timestamppb.Timestamp {
	if x != nil {
		return x.Window
	}
	return nil
}

type GetMetadataVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       []byte                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataVersionResponse) Reset() {
	*x = GetMetadataVersionResponse{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataVersionResponse) ProtoMessage() {}

func (x *GetMetadataVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataVersionResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataVersionResponse) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{13}
}

func (x *GetMetadataVersionResponse) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

type ListMetadataVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowSize    uint32                 `protobuf:"varint,1,opt,name=window_size,json=windowSize,proto3" json:"window_size,omitempty"`
	WindowStart   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMetadataVersionsRequest) Reset() {
	*x = ListMetadataVersionsRequest{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetadataVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetadataVersionsRequest) ProtoMessage() {}

func (x *ListMetadataVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetadataVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListMetadataVersionsRequest) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{14}
}

func (x *ListMetadataVersionsRequest) GetWindowSize() uint32 {
	if x != nil {
		return x.WindowSize
	}
	return 0
}

func (x *ListMetadataVersionsRequest) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *ListMetadataVersionsRequest) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

type ListMetadataVersionsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Windows       []*timestamppb.Timestamp `protobuf:"bytes,1,rep,name=windows,proto3" json:"windows,omitempty"`
	Versions      [][]byte                 `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMetadataVersionsResponse) Reset() {
	*x = ListMetadataVersionsResponse{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetadataVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetadataVersionsResponse) ProtoMessage() {}

func (x *ListMetadataVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetadataVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListMetadataVersionsResponse) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{15}
}

func (x *ListMetadataVersionsResponse) GetWindows() []*timestamppb.Timestamp {
	if x != nil {
		return x.Windows
	}
	return nil
}

func (x *ListMetadataVersionsResponse) GetVersions() [][]byte {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ValidateMetadataVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*Validate            `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMetadataVersionRequest) Reset() {
	*x = ValidateMetadataVersionRequest{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMetadataVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMetadataVersionRequest) ProtoMessage() {}

func (x *ValidateMetadataVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMetadataVersionRequest.ProtoReflect.Descriptor instead.
func (*ValidateMetadataVersionRequest) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateMetadataVersionRequest) GetVersions() []*Validate {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ValidateMetadataVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         []bool                 `protobuf:"varint,1,rep,packed,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMetadataVersionResponse) Reset() {
	*x = ValidateMetadataVersionResponse{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMetadataVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMetadataVersionResponse) ProtoMessage() {}

func (x *ValidateMetadataVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMetadataVersionResponse.ProtoReflect.Descriptor instead.
func (*ValidateMetadataVersionResponse) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateMetadataVersionResponse) GetValid() []bool {
	if x != nil {
		return x.Valid
	}
	return nil
}

type Validate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Window        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=window,proto3" json:"window,omitempty"`
	Version       []byte                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Validate) Reset() {
	*x = Validate{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validate) ProtoMessage() {}

func (x *Validate) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validate.ProtoReflect.Descriptor instead.
func (*Validate) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{18}
}

func (x *Validate) GetWindow() *timestamppb.Timestamp {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *Validate) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

// Immutable metadata describing a partition stored in object storage
type PartitionMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The key used to cluster the data into partitions. This is
	// used to increase data locality, with the idea being that it
	// helps process queries faster
	ClusterKey *ClusterKey `protobuf:"bytes,2,opt,name=cluster_key,json=clusterKey,proto3" json:"cluster_key,omitempty"`
	Segments   []string    `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	// The size in bytes of the Parquet file
	Size     uint64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	RowCount uint64 `protobuf:"varint,5,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	// Time the partition was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Metadata describing the columns in the partition
	Columns       map[string]*Column `protobuf:"bytes,7,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionMetadata) Reset() {
	*x = PartitionMetadata{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionMetadata) ProtoMessage() {}

func (x *PartitionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionMetadata.ProtoReflect.Descriptor instead.
func (*PartitionMetadata) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{19}
}

func (x *PartitionMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PartitionMetadata) GetClusterKey() *ClusterKey {
	if x != nil {
		return x.ClusterKey
	}
	return nil
}

func (x *PartitionMetadata) GetSegments() []string {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *PartitionMetadata) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PartitionMetadata) GetRowCount() uint64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *PartitionMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PartitionMetadata) GetColumns() map[string]*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Statistics    *Statistics            `protobuf:"bytes,2,opt,name=statistics,proto3" json:"statistics,omitempty"`
	Type          ColumnType             `protobuf:"varint,3,opt,name=type,proto3,enum=nexus.metadata.v1.ColumnType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{20}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetStatistics() *Statistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *Column) GetType() ColumnType {
	if x != nil {
		return x.Type
	}
	return ColumnType_COLUMN_TYPE_UNSPECIFIED
}

type Statistics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Min:
	//
	//	*Statistics_MinInt32
	//	*Statistics_MinInt64
	//	*Statistics_MinUint32
	//	*Statistics_MinUint64
	//	*Statistics_MinBool
	//	*Statistics_MinString
	//	*Statistics_MinBytes
	//	*Statistics_MinTimestamp
	Min isStatistics_Min `protobuf_oneof:"min"`
	// Types that are valid to be assigned to Max:
	//
	//	*Statistics_MaxInt32
	//	*Statistics_MaxInt64
	//	*Statistics_MaxUint32
	//	*Statistics_MaxUint64
	//	*Statistics_MaxBool
	//	*Statistics_MaxString
	//	*Statistics_MaxBytes
	//	*Statistics_MaxTimestamp
	Max           isStatistics_Max `protobuf_oneof:"max"`
	Filter        []byte           `protobuf:"bytes,17,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Statistics) Reset() {
	*x = Statistics{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics) ProtoMessage() {}

func (x *Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics.ProtoReflect.Descriptor instead.
func (*Statistics) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{21}
}

func (x *Statistics) GetMin() isStatistics_Min {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *Statistics) GetMinInt32() int32 {
	if x != nil {
		if x, ok := x.Min.(*Statistics_MinInt32); ok {
			return x.MinInt32
		}
	}
	return 0
}

func (x *Statistics) GetMinInt64() int64 {
	if x != nil {
		if x, ok := x.Min.(*Statistics_MinInt64); ok {
			return x.MinInt64
		}
	}
	return 0
}

func (x *Statistics) GetMinUint32() uint32 {
	if x != nil {
		if x, ok := x.Min.(*Statistics_MinUint32); ok {
			return x.MinUint32
		}
	}
	return 0
}

func (x *Statistics) GetMinUint64() uint64 {
	if x != nil {
		if x, ok := x.Min.(*Statistics_MinUint64); ok {
			return x.MinUint64
		}
	}
	return 0
}

func (x *Statistics) GetMinBool() bool {
	if x != nil {
		if x, ok := x.Min.(*Statistics_MinBool); ok {
			return x.MinBool
		}
	}
	return false
}

func (x *Statistics) GetMinString() string {
	if x != nil {
		if x, ok := x.Min.(*Statistics_MinString); ok {
			return x.MinString
		}
	}
	return ""
}

func (x *Statistics) GetMinBytes() []byte {
	if x != nil {
		if x, ok := x.Min.(*Statistics_MinBytes); ok {
			return x.MinBytes
		}
	}
	return nil
}

func (x *Statistics) GetMinTimestamp() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Min.(*Statistics_MinTimestamp); ok {
			return x.MinTimestamp
		}
	}
	return nil
}

func (x *Statistics) GetMax() isStatistics_Max {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *Statistics) GetMaxInt32() int32 {
	if x != nil {
		if x, ok := x.Max.(*Statistics_MaxInt32); ok {
			return x.MaxInt32
		}
	}
	return 0
}

func (x *Statistics) GetMaxInt64() int64 {
	if x != nil {
		if x, ok := x.Max.(*Statistics_MaxInt64); ok {
			return x.MaxInt64
		}
	}
	return 0
}

func (x *Statistics) GetMaxUint32() uint32 {
	if x != nil {
		if x, ok := x.Max.(*Statistics_MaxUint32); ok {
			return x.MaxUint32
		}
	}
	return 0
}

func (x *Statistics) GetMaxUint64() uint64 {
	if x != nil {
		if x, ok := x.Max.(*Statistics_MaxUint64); ok {
			return x.MaxUint64
		}
	}
	return 0
}

func (x *Statistics) GetMaxBool() bool {
	if x != nil {
		if x, ok := x.Max.(*Statistics_MaxBool); ok {
			return x.MaxBool
		}
	}
	return false
}

func (x *Statistics) GetMaxString() string {
	if x != nil {
		if x, ok := x.Max.(*Statistics_MaxString); ok {
			return x.MaxString
		}
	}
	return ""
}

func (x *Statistics) GetMaxBytes() []byte {
	if x != nil {
		if x, ok := x.Max.(*Statistics_MaxBytes); ok {
			return x.MaxBytes
		}
	}
	return nil
}

func (x *Statistics) GetMaxTimestamp() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Max.(*Statistics_MaxTimestamp); ok {
			return x.MaxTimestamp
		}
	}
	return nil
}

func (x *Statistics) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

type isStatistics_Min interface {
	isStatistics_Min()
}

type Statistics_MinInt32 struct {
	// Handles int8, int16, int32
	MinInt32 int32 `protobuf:"varint,1,opt,name=min_int32,json=minInt32,proto3,oneof"`
}

type Statistics_MinInt64 struct {
	MinInt64 int64 `protobuf:"varint,2,opt,name=min_int64,json=minInt64,proto3,oneof"`
}

type Statistics_MinUint32 struct {
	// Handles uint8, uint16, uint32
	MinUint32 uint32 `protobuf:"varint,3,opt,name=min_uint32,json=minUint32,proto3,oneof"`
}

type Statistics_MinUint64 struct {
	MinUint64 uint64 `protobuf:"varint,4,opt,name=min_uint64,json=minUint64,proto3,oneof"`
}

type Statistics_MinBool struct {
	MinBool bool `protobuf:"varint,5,opt,name=min_bool,json=minBool,proto3,oneof"`
}

type Statistics_MinString struct {
	MinString string `protobuf:"bytes,6,opt,name=min_string,json=minString,proto3,oneof"`
}

type Statistics_MinBytes struct {
	MinBytes []byte `protobuf:"bytes,7,opt,name=min_bytes,json=minBytes,proto3,oneof"`
}

type Statistics_MinTimestamp struct {
	MinTimestamp *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=min_timestamp,json=minTimestamp,proto3,oneof"`
}

func (*Statistics_MinInt32) isStatistics_Min() {}

func (*Statistics_MinInt64) isStatistics_Min() {}

func (*Statistics_MinUint32) isStatistics_Min() {}

func (*Statistics_MinUint64) isStatistics_Min() {}

func (*Statistics_MinBool) isStatistics_Min() {}

func (*Statistics_MinString) isStatistics_Min() {}

func (*Statistics_MinBytes) isStatistics_Min() {}

func (*Statistics_MinTimestamp) isStatistics_Min() {}

type isStatistics_Max interface {
	isStatistics_Max()
}

type Statistics_MaxInt32 struct {
	// Handles int8, int16, int32
	MaxInt32 int32 `protobuf:"varint,9,opt,name=max_int32,json=maxInt32,proto3,oneof"`
}

type Statistics_MaxInt64 struct {
	MaxInt64 int64 `protobuf:"varint,10,opt,name=max_int64,json=maxInt64,proto3,oneof"`
}

type Statistics_MaxUint32 struct {
	// Handles uint8, uint16, uint32
	MaxUint32 uint32 `protobuf:"varint,11,opt,name=max_uint32,json=maxUint32,proto3,oneof"`
}

type Statistics_MaxUint64 struct {
	MaxUint64 uint64 `protobuf:"varint,12,opt,name=max_uint64,json=maxUint64,proto3,oneof"`
}

type Statistics_MaxBool struct {
	MaxBool bool `protobuf:"varint,13,opt,name=max_bool,json=maxBool,proto3,oneof"`
}

type Statistics_MaxString struct {
	MaxString string `protobuf:"bytes,14,opt,name=max_string,json=maxString,proto3,oneof"`
}

type Statistics_MaxBytes struct {
	MaxBytes []byte `protobuf:"bytes,15,opt,name=max_bytes,json=maxBytes,proto3,oneof"`
}

type Statistics_MaxTimestamp struct {
	MaxTimestamp *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=max_timestamp,json=maxTimestamp,proto3,oneof"`
}

func (*Statistics_MaxInt32) isStatistics_Max() {}

func (*Statistics_MaxInt64) isStatistics_Max() {}

func (*Statistics_MaxUint32) isStatistics_Max() {}

func (*Statistics_MaxUint64) isStatistics_Max() {}

func (*Statistics_MaxBool) isStatistics_Max() {}

func (*Statistics_MaxString) isStatistics_Max() {}

func (*Statistics_MaxBytes) isStatistics_Max() {}

func (*Statistics_MaxTimestamp) isStatistics_Max() {}

type ClusterKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp is the time that the flow was received
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The ID of the device the flow belongs to
	DeviceId      uint64 `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterKey) Reset() {
	*x = ClusterKey{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterKey) ProtoMessage() {}

func (x *ClusterKey) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterKey.ProtoReflect.Descriptor instead.
func (*ClusterKey) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{22}
}

func (x *ClusterKey) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ClusterKey) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

// TODO: Add metrics we care about?
type Compaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Level         CompactionLevel        `protobuf:"varint,2,opt,name=level,proto3,enum=nexus.metadata.v1.CompactionLevel" json:"level,omitempty"`
	Window        *Window                `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Compaction) Reset() {
	*x = Compaction{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compaction) ProtoMessage() {}

func (x *Compaction) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compaction.ProtoReflect.Descriptor instead.
func (*Compaction) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{23}
}

func (x *Compaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Compaction) GetLevel() CompactionLevel {
	if x != nil {
		return x.Level
	}
	return CompactionLevel_COMPACTION_LEVEL_UNSPECIFIED
}

func (x *Compaction) GetWindow() *Window {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *Compaction) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Window struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Window) Reset() {
	*x = Window{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Window) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Window) ProtoMessage() {}

func (x *Window) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Window.ProtoReflect.Descriptor instead.
func (*Window) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{24}
}

func (x *Window) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Window) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Window) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// Metadata and data stored for a given value
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// int32 enc = 2; // encoding of the raw data -- store as enums
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Comp          Compression            `protobuf:"varint,3,opt,name=comp,proto3,enum=nexus.metadata.v1.Compression" json:"comp,omitempty"`
	Raw           []byte                 `protobuf:"bytes,4,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{25}
}

func (x *Value) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Value) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Value) GetComp() Compression {
	if x != nil {
		return x.Comp
	}
	return Compression_COMPRESSION_UNSPECIFIED
}

func (x *Value) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type Variant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Variant:
	//
	//	*Variant_Int32Variant
	//	*Variant_Int64Variant
	//	*Variant_Uint32Variant
	//	*Variant_Uint64Variant
	//	*Variant_BoolVariant
	//	*Variant_StringVariant
	//	*Variant_BytesVariant
	//	*Variant_TimestampVariant
	Variant       isVariant_Variant `protobuf_oneof:"variant"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_metadata_v1_metadata_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_nexus_metadata_v1_metadata_proto_rawDescGZIP(), []int{26}
}

func (x *Variant) GetVariant() isVariant_Variant {
	if x != nil {
		return x.Variant
	}
	return nil
}

func (x *Variant) GetInt32Variant() int32 {
	if x != nil {
		if x, ok := x.Variant.(*Variant_Int32Variant); ok {
			return x.Int32Variant
		}
	}
	return 0
}

func (x *Variant) GetInt64Variant() int64 {
	if x != nil {
		if x, ok := x.Variant.(*Variant_Int64Variant); ok {
			return x.Int64Variant
		}
	}
	return 0
}

func (x *Variant) GetUint32Variant() uint32 {
	if x != nil {
		if x, ok := x.Variant.(*Variant_Uint32Variant); ok {
			return x.Uint32Variant
		}
	}
	return 0
}

func (x *Variant) GetUint64Variant() uint64 {
	if x != nil {
		if x, ok := x.Variant.(*Variant_Uint64Variant); ok {
			return x.Uint64Variant
		}
	}
	return 0
}

func (x *Variant) GetBoolVariant() bool {
	if x != nil {
		if x, ok := x.Variant.(*Variant_BoolVariant); ok {
			return x.BoolVariant
		}
	}
	return false
}

func (x *Variant) GetStringVariant() string {
	if x != nil {
		if x, ok := x.Variant.(*Variant_StringVariant); ok {
			return x.StringVariant
		}
	}
	return ""
}

func (x *Variant) GetBytesVariant() []byte {
	if x != nil {
		if x, ok := x.Variant.(*Variant_BytesVariant); ok {
			return x.BytesVariant
		}
	}
	return nil
}

func (x *Variant) GetTimestampVariant() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Variant.(*Variant_TimestampVariant); ok {
			return x.TimestampVariant
		}
	}
	return nil
}

type isVariant_Variant interface {
	isVariant_Variant()
}

type Variant_Int32Variant struct {
	Int32Variant int32 `protobuf:"varint,1,opt,name=int32_variant,json=int32Variant,proto3,oneof"`
}

type Variant_Int64Variant struct {
	Int64Variant int64 `protobuf:"varint,2,opt,name=int64_variant,json=int64Variant,proto3,oneof"`
}

type Variant_Uint32Variant struct {
	Uint32Variant uint32 `protobuf:"varint,3,opt,name=uint32_variant,json=uint32Variant,proto3,oneof"`
}

type Variant_Uint64Variant struct {
	Uint64Variant uint64 `protobuf:"varint,4,opt,name=uint64_variant,json=uint64Variant,proto3,oneof"`
}

type Variant_BoolVariant struct {
	BoolVariant bool `protobuf:"varint,5,opt,name=bool_variant,json=boolVariant,proto3,oneof"`
}

type Variant_StringVariant struct {
	StringVariant string `protobuf:"bytes,6,opt,name=string_variant,json=stringVariant,proto3,oneof"`
}

type Variant_BytesVariant struct {
	BytesVariant []byte `protobuf:"bytes,7,opt,name=bytes_variant,json=bytesVariant,proto3,oneof"`
}

type Variant_TimestampVariant struct {
	TimestampVariant *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp_variant,json=timestampVariant,proto3,oneof"`
}

func (*Variant_Int32Variant) isVariant_Variant() {}

func (*Variant_Int64Variant) isVariant_Variant() {}

func (*Variant_Uint32Variant) isVariant_Variant() {}

func (*Variant_Uint64Variant) isVariant_Variant() {}

func (*Variant_BoolVariant) isVariant_Variant() {}

func (*Variant_StringVariant) isVariant_Variant() {}

func (*Variant_BytesVariant) isVariant_Variant() {}

func (*Variant_TimestampVariant) isVariant_Variant() {}

var File_nexus_metadata_v1_metadata_proto protoreflect.FileDescriptor

const file_nexus_metadata_v1_metadata_proto_rawDesc = "" +
	"\n" +
	" nexus/metadata/v1/metadata.proto\x12\x11nexus.metadata.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n" +
	"\x19CreateOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x1aCreateOrganizationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"+\n" +
	"\x19DeleteOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x1aDeleteOrganizationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"L\n" +
	"\x11CreateTeamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"\x88\x01\n" +
	"\x12CreateTeamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"L\n" +
	"\x11DeleteTeamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"\x88\x01\n" +
	"\x12DeleteTeamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xde\x01\n" +
	"\x16CreatePartitionRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12S\n" +
	"\x12partition_metadata\x18\x05 \x01(\v2$.nexus.metadata.v1.PartitionMetadataR\x11partitionMetadata\"\x9a\x02\n" +
	"\x17CreatePartitionResponse\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12S\n" +
	"\x12partition_metadata\x18\x05 \x01(\v2$.nexus.metadata.v1.PartitionMetadataR\x11partitionMetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xea\x01\n" +
	"\x15ListPartitionsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xc0\x02\n" +
	"\x16ListPartitionsResponse\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12S\n" +
	"\x12partition_metadata\x18\x06 \x03(\v2$.nexus.metadata.v1.PartitionMetadataR\x11partitionMetadata\"p\n" +
	"\x19GetMetadataVersionRequest\x12\x1f\n" +
	"\vwindow_size\x18\x01 \x01(\rR\n" +
	"windowSize\x122\n" +
	"\x06window\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06window\"6\n" +
	"\x1aGetMetadataVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\fR\aversion\"\xb8\x01\n" +
	"\x1bListMetadataVersionsRequest\x12\x1f\n" +
	"\vwindow_size\x18\x01 \x01(\rR\n" +
	"windowSize\x12=\n" +
	"\fwindow_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x129\n" +
	"\n" +
	"window_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\twindowEnd\"p\n" +
	"\x1cListMetadataVersionsResponse\x124\n" +
	"\awindows\x18\x01 \x03(\v2\x1a.google.protobuf.TimestampR\awindows\x12\x1a\n" +
	"\bversions\x18\x02 \x03(\fR\bversions\"Y\n" +
	"\x1eValidateMetadataVersionRequest\x127\n" +
	"\bversions\x18\x01 \x03(\v2\x1b.nexus.metadata.v1.ValidateR\bversions\"7\n" +
	"\x1fValidateMetadataVersionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x03(\bR\x05valid\"X\n" +
	"\bValidate\x122\n" +
	"\x06window\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06window\x12\x18\n" +
	"\aversion\x18\x02 \x01(\fR\aversion\"\x8f\x03\n" +
	"\x11PartitionMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\vcluster_key\x18\x02 \x01(\v2\x1d.nexus.metadata.v1.ClusterKeyR\n" +
	"clusterKey\x12\x1a\n" +
	"\bsegments\x18\x03 \x03(\tR\bsegments\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x1b\n" +
	"\trow_count\x18\x05 \x01(\x04R\browCount\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12K\n" +
	"\acolumns\x18\a \x03(\v21.nexus.metadata.v1.PartitionMetadata.ColumnsEntryR\acolumns\x1aU\n" +
	"\fColumnsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.nexus.metadata.v1.ColumnR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x06Column\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\n" +
	"statistics\x18\x02 \x01(\v2\x1d.nexus.metadata.v1.StatisticsR\n" +
	"statistics\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.nexus.metadata.v1.ColumnTypeR\x04type\"\xf2\x04\n" +
	"\n" +
	"Statistics\x12\x1d\n" +
	"\tmin_int32\x18\x01 \x01(\x05H\x00R\bminInt32\x12\x1d\n" +
	"\tmin_int64\x18\x02 \x01(\x03H\x00R\bminInt64\x12\x1f\n" +
	"\n" +
	"min_uint32\x18\x03 \x01(\rH\x00R\tminUint32\x12\x1f\n" +
	"\n" +
	"min_uint64\x18\x04 \x01(\x04H\x00R\tminUint64\x12\x1b\n" +
	"\bmin_bool\x18\x05 \x01(\bH\x00R\aminBool\x12\x1f\n" +
	"\n" +
	"min_string\x18\x06 \x01(\tH\x00R\tminString\x12\x1d\n" +
	"\tmin_bytes\x18\a \x01(\fH\x00R\bminBytes\x12A\n" +
	"\rmin_timestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\fminTimestamp\x12\x1d\n" +
	"\tmax_int32\x18\t \x01(\x05H\x01R\bmaxInt32\x12\x1d\n" +
	"\tmax_int64\x18\n" +
	" \x01(\x03H\x01R\bmaxInt64\x12\x1f\n" +
	"\n" +
	"max_uint32\x18\v \x01(\rH\x01R\tmaxUint32\x12\x1f\n" +
	"\n" +
	"max_uint64\x18\f \x01(\x04H\x01R\tmaxUint64\x12\x1b\n" +
	"\bmax_bool\x18\r \x01(\bH\x01R\amaxBool\x12\x1f\n" +
	"\n" +
	"max_string\x18\x0e \x01(\tH\x01R\tmaxString\x12\x1d\n" +
	"\tmax_bytes\x18\x0f \x01(\fH\x01R\bmaxBytes\x12A\n" +
	"\rmax_timestamp\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\fmaxTimestamp\x12\x16\n" +
	"\x06filter\x18\x11 \x01(\fR\x06filterB\x05\n" +
	"\x03minB\x05\n" +
	"\x03max\"c\n" +
	"\n" +
	"ClusterKey\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\x04R\bdeviceId\"\xc8\x01\n" +
	"\n" +
	"Compaction\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\x05level\x18\x02 \x01(\x0e2\".nexus.metadata.v1.CompactionLevelR\x05level\x121\n" +
	"\x06window\x18\x03 \x01(\v2\x19.nexus.metadata.v1.WindowR\x06window\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\"\x8e\x01\n" +
	"\x06Window\x12\x12\n" +
	"\x04size\x18\x01 \x01(\rR\x04size\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xc3\x01\n" +
	"\x05Value\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x122\n" +
	"\x04comp\x18\x03 \x01(\x0e2\x1e.nexus.metadata.v1.CompressionR\x04comp\x12\x10\n" +
	"\x03raw\x18\x04 \x01(\fR\x03raw\"\xf4\x02\n" +
	"\aVariant\x12%\n" +
	"\rint32_variant\x18\x01 \x01(\x05H\x00R\fint32Variant\x12%\n" +
	"\rint64_variant\x18\x02 \x01(\x03H\x00R\fint64Variant\x12'\n" +
	"\x0euint32_variant\x18\x03 \x01(\rH\x00R\ruint32Variant\x12'\n" +
	"\x0euint64_variant\x18\x04 \x01(\x04H\x00R\ruint64Variant\x12#\n" +
	"\fbool_variant\x18\x05 \x01(\bH\x00R\vboolVariant\x12'\n" +
	"\x0estring_variant\x18\x06 \x01(\tH\x00R\rstringVariant\x12%\n" +
	"\rbytes_variant\x18\a \x01(\fH\x00R\fbytesVariant\x12I\n" +
	"\x11timestamp_variant\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x10timestampVariantB\t\n" +
	"\avariant*\xc6\x02\n" +
	"\n" +
	"ColumnType\x12\x1b\n" +
	"\x17COLUMN_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COLUMN_TYPE_INT8\x10\x01\x12\x15\n" +
	"\x11COLUMN_TYPE_INT16\x10\x02\x12\x15\n" +
	"\x11COLUMN_TYPE_INT32\x10\x03\x12\x15\n" +
	"\x11COLUMN_TYPE_INT64\x10\x04\x12\x15\n" +
	"\x11COLUMN_TYPE_UINT8\x10\x05\x12\x16\n" +
	"\x12COLUMN_TYPE_UINT16\x10\x06\x12\x16\n" +
	"\x12COLUMN_TYPE_UINT32\x10\a\x12\x16\n" +
	"\x12COLUMN_TYPE_UINT64\x10\b\x12\x16\n" +
	"\x12COLUMN_TYPE_STRING\x10\t\x12\x17\n" +
	"\x13COLUMN_TYPE_BOOLEAN\x10\n" +
	"\x12\x19\n" +
	"\x15COLUMN_TYPE_TIMESTAMP\x10\v\x12\x15\n" +
	"\x11COLUMN_TYPE_BYTES\x10\f*h\n" +
	"\x0fCompactionLevel\x12 \n" +
	"\x1cCOMPACTION_LEVEL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COMPACTION_LEVEL_ZERO\x10\x01\x12\x18\n" +
	"\x14COMPACTION_LEVEL_ONE\x10\x02*m\n" +
	"\vCompression\x12\x1b\n" +
	"\x17COMPRESSION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_ZSTD\x10\x01\x12\x13\n" +
	"\x0fCOMPRESSION_LZ4\x10\x02\x12\x16\n" +
	"\x12COMPRESSION_SNAPPY\x10\x032\xff\a\n" +
	"\x0fMetadataService\x12s\n" +
	"\x12CreateOrganization\x12,.nexus.metadata.v1.CreateOrganizationRequest\x1a-.nexus.metadata.v1.CreateOrganizationResponse\"\x00\x12s\n" +
	"\x12DeleteOrganization\x12,.nexus.metadata.v1.DeleteOrganizationRequest\x1a-.nexus.metadata.v1.DeleteOrganizationResponse\"\x00\x12[\n" +
	"\n" +
	"CreateTeam\x12$.nexus.metadata.v1.CreateTeamRequest\x1a%.nexus.metadata.v1.CreateTeamResponse\"\x00\x12[\n" +
	"\n" +
	"DeleteTeam\x12$.nexus.metadata.v1.DeleteTeamRequest\x1a%.nexus.metadata.v1.DeleteTeamResponse\"\x00\x12j\n" +
	"\x0fCreatePartition\x12).nexus.metadata.v1.CreatePartitionRequest\x1a*.nexus.metadata.v1.CreatePartitionResponse\"\x00\x12g\n" +
	"\x0eListPartitions\x12(.nexus.metadata.v1.ListPartitionsRequest\x1a).nexus.metadata.v1.ListPartitionsResponse\"\x00\x12\x82\x01\n" +
	"\x17ValidateMetadataVersion\x121.nexus.metadata.v1.ValidateMetadataVersionRequest\x1a2.nexus.metadata.v1.ValidateMetadataVersionResponse\"\x00\x12s\n" +
	"\x12GetMetadataVersion\x12,.nexus.metadata.v1.GetMetadataVersionRequest\x1a-.nexus.metadata.v1.GetMetadataVersionResponse\"\x00\x12y\n" +
	"\x14ListMetadataVersions\x12..nexus.metadata.v1.ListMetadataVersionsRequest\x1a/.nexus.metadata.v1.ListMetadataVersionsResponse\"\x00B>Z<github.com/liquidspill/proto/go/nexus/metadata/v1;metadatav1b\x06proto3"

var (
	file_nexus_metadata_v1_metadata_proto_rawDescOnce sync.Once
	file_nexus_metadata_v1_metadata_proto_rawDescData []byte
)

func file_nexus_metadata_v1_metadata_proto_rawDescGZIP() []byte {
	file_nexus_metadata_v1_metadata_proto_rawDescOnce.Do(func() {
		file_nexus_metadata_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_metadata_v1_metadata_proto_rawDesc), len(file_nexus_metadata_v1_metadata_proto_rawDesc)))
	})
	return file_nexus_metadata_v1_metadata_proto_rawDescData
}

var file_nexus_metadata_v1_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_nexus_metadata_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_nexus_metadata_v1_metadata_proto_goTypes = []any{
	(ColumnType)(0),                         // 0: nexus.metadata.v1.ColumnType
	(CompactionLevel)(0),                    // 1: nexus.metadata.v1.CompactionLevel
	(Compression)(0),                        // 2: nexus.metadata.v1.Compression
	(*CreateOrganizationRequest)(nil),       // 3: nexus.metadata.v1.CreateOrganizationRequest
	(*CreateOrganizationResponse)(nil),      // 4: nexus.metadata.v1.CreateOrganizationResponse
	(*DeleteOrganizationRequest)(nil),       // 5: nexus.metadata.v1.DeleteOrganizationRequest
	(*DeleteOrganizationResponse)(nil),      // 6: nexus.metadata.v1.DeleteOrganizationResponse
	(*CreateTeamRequest)(nil),               // 7: nexus.metadata.v1.CreateTeamRequest
	(*CreateTeamResponse)(nil),              // 8: nexus.metadata.v1.CreateTeamResponse
	(*DeleteTeamRequest)(nil),               // 9: nexus.metadata.v1.DeleteTeamRequest
	(*DeleteTeamResponse)(nil),              // 10: nexus.metadata.v1.DeleteTeamResponse
	(*CreatePartitionRequest)(nil),          // 11: nexus.metadata.v1.CreatePartitionRequest
	(*CreatePartitionResponse)(nil),         // 12: nexus.metadata.v1.CreatePartitionResponse
	(*ListPartitionsRequest)(nil),           // 13: nexus.metadata.v1.ListPartitionsRequest
	(*ListPartitionsResponse)(nil),          // 14: nexus.metadata.v1.ListPartitionsResponse
	(*GetMetadataVersionRequest)(nil),       // 15: nexus.metadata.v1.GetMetadataVersionRequest
	(*GetMetadataVersionResponse)(nil),      // 16: nexus.metadata.v1.GetMetadataVersionResponse
	(*ListMetadataVersionsRequest)(nil),     // 17: nexus.metadata.v1.ListMetadataVersionsRequest
	(*ListMetadataVersionsResponse)(nil),    // 18: nexus.metadata.v1.ListMetadataVersionsResponse
	(*ValidateMetadataVersionRequest)(nil),  // 19: nexus.metadata.v1.ValidateMetadataVersionRequest
	(*ValidateMetadataVersionResponse)(nil), // 20: nexus.metadata.v1.ValidateMetadataVersionResponse
	(*Validate)(nil),                        // 21: nexus.metadata.v1.Validate
	(*PartitionMetadata)(nil),               // 22: nexus.metadata.v1.PartitionMetadata
	(*Column)(nil),                          // 23: nexus.metadata.v1.Column
	(*Statistics)(nil),                      // 24: nexus.metadata.v1.Statistics
	(*ClusterKey)(nil),                      // 25: nexus.metadata.v1.ClusterKey
	(*Compaction)(nil),                      // 26: nexus.metadata.v1.Compaction
	(*Window)(nil),                          // 27: nexus.metadata.v1.Window
	(*Value)(nil),                           // 28: nexus.metadata.v1.Value
	(*Variant)(nil),                         // 29: nexus.metadata.v1.Variant
	nil,                                     // 30: nexus.metadata.v1.PartitionMetadata.ColumnsEntry
	(*timestamppb.Timestamp)(nil),           // 31: google.protobuf.Timestamp
}
var file_nexus_metadata_v1_metadata_proto_depIdxs = []int32{
	31, // 0: nexus.metadata.v1.CreateOrganizationResponse.created_at:type_name -> google.protobuf.Timestamp
	31, // 1: nexus.metadata.v1.DeleteOrganizationResponse.deleted_at:type_name -> google.protobuf.Timestamp
	31, // 2: nexus.metadata.v1.CreateTeamResponse.created_at:type_name -> google.protobuf.Timestamp
	31, // 3: nexus.metadata.v1.DeleteTeamResponse.deleted_at:type_name -> google.protobuf.Timestamp
	22, // 4: nexus.metadata.v1.CreatePartitionRequest.partition_metadata:type_name -> nexus.metadata.v1.PartitionMetadata
	22, // 5: nexus.metadata.v1.CreatePartitionResponse.partition_metadata:type_name -> nexus.metadata.v1.PartitionMetadata
	31, // 6: nexus.metadata.v1.CreatePartitionResponse.created_at:type_name -> google.protobuf.Timestamp
	31, // 7: nexus.metadata.v1.ListPartitionsRequest.start_time:type_name -> google.protobuf.Timestamp
	31, // 8: nexus.metadata.v1.ListPartitionsRequest.end_time:type_name -> google.protobuf.Timestamp
	31, // 9: nexus.metadata.v1.ListPartitionsResponse.start_time:type_name -> google.protobuf.Timestamp
	31, // 10: nexus.metadata.v1.ListPartitionsResponse.end_time:type_name -> google.protobuf.Timestamp
	22, // 11: nexus.metadata.v1.ListPartitionsResponse.partition_metadata:type_name -> nexus.metadata.v1.PartitionMetadata
	31, // 12: nexus.metadata.v1.GetMetadataVersionRequest.window:type_name -> google.protobuf.Timestamp
	31, // 13: nexus.metadata.v1.ListMetadataVersionsRequest.window_start:type_name -> google.protobuf.Timestamp
	31, // 14: nexus.metadata.v1.ListMetadataVersionsRequest.window_end:type_name -> google.protobuf.Timestamp
	31, // 15: nexus.metadata.v1.ListMetadataVersionsResponse.windows:type_name -> google.protobuf.Timestamp
	21, // 16: nexus.metadata.v1.ValidateMetadataVersionRequest.versions:type_name -> nexus.metadata.v1.Validate
	31, // 17: nexus.metadata.v1.Validate.window:type_name -> google.protobuf.Timestamp
	25, // 18: nexus.metadata.v1.PartitionMetadata.cluster_key:type_name -> nexus.metadata.v1.ClusterKey
	31, // 19: nexus.metadata.v1.PartitionMetadata.created_at:type_name -> google.protobuf.Timestamp
	30, // 20: nexus.metadata.v1.PartitionMetadata.columns:type_name -> nexus.metadata.v1.PartitionMetadata.ColumnsEntry
	24, // 21: nexus.metadata.v1.Column.statistics:type_name -> nexus.metadata.v1.Statistics
	0,  // 22: nexus.metadata.v1.Column.type:type_name -> nexus.metadata.v1.ColumnType
	31, // 23: nexus.metadata.v1.Statistics.min_timestamp:type_name -> google.protobuf.Timestamp
	31, // 24: nexus.metadata.v1.Statistics.max_timestamp:type_name -> google.protobuf.Timestamp
	31, // 25: nexus.metadata.v1.ClusterKey.timestamp:type_name -> google.protobuf.Timestamp
	31, // 26: nexus.metadata.v1.Compaction.created_at:type_name -> google.protobuf.Timestamp
	1,  // 27: nexus.metadata.v1.Compaction.level:type_name -> nexus.metadata.v1.CompactionLevel
	27, // 28: nexus.metadata.v1.Compaction.window:type_name -> nexus.metadata.v1.Window
	31, // 29: nexus.metadata.v1.Window.start_time:type_name -> google.protobuf.Timestamp
	31, // 30: nexus.metadata.v1.Window.end_time:type_name -> google.protobuf.Timestamp
	31, // 31: nexus.metadata.v1.Value.created_at:type_name -> google.protobuf.Timestamp
	31, // 32: nexus.metadata.v1.Value.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 33: nexus.metadata.v1.Value.comp:type_name -> nexus.metadata.v1.Compression
	31, // 34: nexus.metadata.v1.Variant.timestamp_variant:type_name -> google.protobuf.Timestamp
	23, // 35: nexus.metadata.v1.PartitionMetadata.ColumnsEntry.value:type_name -> nexus.metadata.v1.Column
	3,  // 36: nexus.metadata.v1.MetadataService.CreateOrganization:input_type -> nexus.metadata.v1.CreateOrganizationRequest
	5,  // 37: nexus.metadata.v1.MetadataService.DeleteOrganization:input_type -> nexus.metadata.v1.DeleteOrganizationRequest
	7,  // 38: nexus.metadata.v1.MetadataService.CreateTeam:input_type -> nexus.metadata.v1.CreateTeamRequest
	9,  // 39: nexus.metadata.v1.MetadataService.DeleteTeam:input_type -> nexus.metadata.v1.DeleteTeamRequest
	11, // 40: nexus.metadata.v1.MetadataService.CreatePartition:input_type -> nexus.metadata.v1.CreatePartitionRequest
	13, // 41: nexus.metadata.v1.MetadataService.ListPartitions:input_type -> nexus.metadata.v1.ListPartitionsRequest
	19, // 42: nexus.metadata.v1.MetadataService.ValidateMetadataVersion:input_type -> nexus.metadata.v1.ValidateMetadataVersionRequest
	15, // 43: nexus.metadata.v1.MetadataService.GetMetadataVersion:input_type -> nexus.metadata.v1.GetMetadataVersionRequest
	17, // 44: nexus.metadata.v1.MetadataService.ListMetadataVersions:input_type -> nexus.metadata.v1.ListMetadataVersionsRequest
	4,  // 45: nexus.metadata.v1.MetadataService.CreateOrganization:output_type -> nexus.metadata.v1.CreateOrganizationResponse
	6,  // 46: nexus.metadata.v1.MetadataService.DeleteOrganization:output_type -> nexus.metadata.v1.DeleteOrganizationResponse
	8,  // 47: nexus.metadata.v1.MetadataService.CreateTeam:output_type -> nexus.metadata.v1.CreateTeamResponse
	10, // 48: nexus.metadata.v1.MetadataService.DeleteTeam:output_type -> nexus.metadata.v1.DeleteTeamResponse
	12, // 49: nexus.metadata.v1.MetadataService.CreatePartition:output_type -> nexus.metadata.v1.CreatePartitionResponse
	14, // 50: nexus.metadata.v1.MetadataService.ListPartitions:output_type -> nexus.metadata.v1.ListPartitionsResponse
	20, // 51: nexus.metadata.v1.MetadataService.ValidateMetadataVersion:output_type -> nexus.metadata.v1.ValidateMetadataVersionResponse
	16, // 52: nexus.metadata.v1.MetadataService.GetMetadataVersion:output_type -> nexus.metadata.v1.GetMetadataVersionResponse
	18, // 53: nexus.metadata.v1.MetadataService.ListMetadataVersions:output_type -> nexus.metadata.v1.ListMetadataVersionsResponse
	45, // [45:54] is the sub-list for method output_type
	36, // [36:45] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_nexus_metadata_v1_metadata_proto_init() }
func file_nexus_metadata_v1_metadata_proto_init() {
	if File_nexus_metadata_v1_metadata_proto != nil {
		return
	}
	file_nexus_metadata_v1_metadata_proto_msgTypes[21].OneofWrappers = []any{
		(*Statistics_MinInt32)(nil),
		(*Statistics_MinInt64)(nil),
		(*Statistics_MinUint32)(nil),
		(*Statistics_MinUint64)(nil),
		(*Statistics_MinBool)(nil),
		(*Statistics_MinString)(nil),
		(*Statistics_MinBytes)(nil),
		(*Statistics_MinTimestamp)(nil),
		(*Statistics_MaxInt32)(nil),
		(*Statistics_MaxInt64)(nil),
		(*Statistics_MaxUint32)(nil),
		(*Statistics_MaxUint64)(nil),
		(*Statistics_MaxBool)(nil),
		(*Statistics_MaxString)(nil),
		(*Statistics_MaxBytes)(nil),
		(*Statistics_MaxTimestamp)(nil),
	}
	file_nexus_metadata_v1_metadata_proto_msgTypes[26].OneofWrappers = []any{
		(*Variant_Int32Variant)(nil),
		(*Variant_Int64Variant)(nil),
		(*Variant_Uint32Variant)(nil),
		(*Variant_Uint64Variant)(nil),
		(*Variant_BoolVariant)(nil),
		(*Variant_StringVariant)(nil),
		(*Variant_BytesVariant)(nil),
		(*Variant_TimestampVariant)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_metadata_v1_metadata_proto_rawDesc), len(file_nexus_metadata_v1_metadata_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_metadata_v1_metadata_proto_goTypes,
		DependencyIndexes: file_nexus_metadata_v1_metadata_proto_depIdxs,
		EnumInfos:         file_nexus_metadata_v1_metadata_proto_enumTypes,
		MessageInfos:      file_nexus_metadata_v1_metadata_proto_msgTypes,
	}.Build()
	File_nexus_metadata_v1_metadata_proto = out.File
	file_nexus_metadata_v1_metadata_proto_goTypes = nil
	file_nexus_metadata_v1_metadata_proto_depIdxs = nil
}
