// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: nexus/organization/v1/organization.proto

package organizationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterOrganizationRequest) Reset() {
	*x = RegisterOrganizationRequest{}
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOrganizationRequest) ProtoMessage() {}

func (x *RegisterOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOrganizationRequest.ProtoReflect.Descriptor instead.
func (*RegisterOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_nexus_organization_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegisterOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterOrganizationResponse) Reset() {
	*x = RegisterOrganizationResponse{}
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOrganizationResponse) ProtoMessage() {}

func (x *RegisterOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOrganizationResponse.ProtoReflect.Descriptor instead.
func (*RegisterOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_nexus_organization_v1_organization_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterOrganizationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterOrganizationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeregisterOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterOrganizationRequest) Reset() {
	*x = DeregisterOrganizationRequest{}
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterOrganizationRequest) ProtoMessage() {}

func (x *DeregisterOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterOrganizationRequest.ProtoReflect.Descriptor instead.
func (*DeregisterOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_nexus_organization_v1_organization_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeregisterOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterOrganizationResponse) Reset() {
	*x = DeregisterOrganizationResponse{}
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterOrganizationResponse) ProtoMessage() {}

func (x *DeregisterOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterOrganizationResponse.ProtoReflect.Descriptor instead.
func (*DeregisterOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_nexus_organization_v1_organization_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterOrganizationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeregisterOrganizationResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type RegisterTeamRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterTeamRequest) Reset() {
	*x = RegisterTeamRequest{}
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTeamRequest) ProtoMessage() {}

func (x *RegisterTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTeamRequest.ProtoReflect.Descriptor instead.
func (*RegisterTeamRequest) Descriptor() ([]byte, []int) {
	return file_nexus_organization_v1_organization_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterTeamRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type RegisterTeamResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterTeamResponse) Reset() {
	*x = RegisterTeamResponse{}
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTeamResponse) ProtoMessage() {}

func (x *RegisterTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTeamResponse.ProtoReflect.Descriptor instead.
func (*RegisterTeamResponse) Descriptor() ([]byte, []int) {
	return file_nexus_organization_v1_organization_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterTeamResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterTeamResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RegisterTeamResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeregisterTeamRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeregisterTeamRequest) Reset() {
	*x = DeregisterTeamRequest{}
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterTeamRequest) ProtoMessage() {}

func (x *DeregisterTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterTeamRequest.ProtoReflect.Descriptor instead.
func (*DeregisterTeamRequest) Descriptor() ([]byte, []int) {
	return file_nexus_organization_v1_organization_proto_rawDescGZIP(), []int{6}
}

func (x *DeregisterTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeregisterTeamRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type DeregisterTeamResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeregisterTeamResponse) Reset() {
	*x = DeregisterTeamResponse{}
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterTeamResponse) ProtoMessage() {}

func (x *DeregisterTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_organization_v1_organization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterTeamResponse.ProtoReflect.Descriptor instead.
func (*DeregisterTeamResponse) Descriptor() ([]byte, []int) {
	return file_nexus_organization_v1_organization_proto_rawDescGZIP(), []int{7}
}

func (x *DeregisterTeamResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeregisterTeamResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DeregisterTeamResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_nexus_organization_v1_organization_proto protoreflect.FileDescriptor

const file_nexus_organization_v1_organization_proto_rawDesc = "" +
	"\n" +
	"(nexus/organization/v1/organization.proto\x12\x15nexus.organization.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n" +
	"\x1bRegisterOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"i\n" +
	"\x1cRegisterOrganizationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"/\n" +
	"\x1dDeregisterOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"k\n" +
	"\x1eDeregisterOrganizationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"N\n" +
	"\x13RegisterTeamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"\x8a\x01\n" +
	"\x14RegisterTeamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"P\n" +
	"\x15DeregisterTeamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"\x8c\x01\n" +
	"\x16DeregisterTeamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt2\xff\x03\n" +
	"\x13OrganizationService\x12\x81\x01\n" +
	"\x14RegisterOrganization\x122.nexus.organization.v1.RegisterOrganizationRequest\x1a3.nexus.organization.v1.RegisterOrganizationResponse\"\x00\x12\x87\x01\n" +
	"\x16DeregisterOrganization\x124.nexus.organization.v1.DeregisterOrganizationRequest\x1a5.nexus.organization.v1.DeregisterOrganizationResponse\"\x00\x12i\n" +
	"\fRegisterTeam\x12*.nexus.organization.v1.RegisterTeamRequest\x1a+.nexus.organization.v1.RegisterTeamResponse\"\x00\x12o\n" +
	"\x0eDeregisterTeam\x12,.nexus.organization.v1.DeregisterTeamRequest\x1a-.nexus.organization.v1.DeregisterTeamResponse\"\x00BFZDgithub.com/liquidspill/proto/go/nexus/organization/v1;organizationv1b\x06proto3"

var (
	file_nexus_organization_v1_organization_proto_rawDescOnce sync.Once
	file_nexus_organization_v1_organization_proto_rawDescData []byte
)

func file_nexus_organization_v1_organization_proto_rawDescGZIP() []byte {
	file_nexus_organization_v1_organization_proto_rawDescOnce.Do(func() {
		file_nexus_organization_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_organization_v1_organization_proto_rawDesc), len(file_nexus_organization_v1_organization_proto_rawDesc)))
	})
	return file_nexus_organization_v1_organization_proto_rawDescData
}

var file_nexus_organization_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_nexus_organization_v1_organization_proto_goTypes = []any{
	(*RegisterOrganizationRequest)(nil),    // 0: nexus.organization.v1.RegisterOrganizationRequest
	(*RegisterOrganizationResponse)(nil),   // 1: nexus.organization.v1.RegisterOrganizationResponse
	(*DeregisterOrganizationRequest)(nil),  // 2: nexus.organization.v1.DeregisterOrganizationRequest
	(*DeregisterOrganizationResponse)(nil), // 3: nexus.organization.v1.DeregisterOrganizationResponse
	(*RegisterTeamRequest)(nil),            // 4: nexus.organization.v1.RegisterTeamRequest
	(*RegisterTeamResponse)(nil),           // 5: nexus.organization.v1.RegisterTeamResponse
	(*DeregisterTeamRequest)(nil),          // 6: nexus.organization.v1.DeregisterTeamRequest
	(*DeregisterTeamResponse)(nil),         // 7: nexus.organization.v1.DeregisterTeamResponse
	(*timestamppb.Timestamp)(nil),          // 8: google.protobuf.Timestamp
}
var file_nexus_organization_v1_organization_proto_depIdxs = []int32{
	8, // 0: nexus.organization.v1.RegisterOrganizationResponse.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: nexus.organization.v1.DeregisterOrganizationResponse.deleted_at:type_name -> google.protobuf.Timestamp
	8, // 2: nexus.organization.v1.RegisterTeamResponse.created_at:type_name -> google.protobuf.Timestamp
	8, // 3: nexus.organization.v1.DeregisterTeamResponse.deleted_at:type_name -> google.protobuf.Timestamp
	0, // 4: nexus.organization.v1.OrganizationService.RegisterOrganization:input_type -> nexus.organization.v1.RegisterOrganizationRequest
	2, // 5: nexus.organization.v1.OrganizationService.DeregisterOrganization:input_type -> nexus.organization.v1.DeregisterOrganizationRequest
	4, // 6: nexus.organization.v1.OrganizationService.RegisterTeam:input_type -> nexus.organization.v1.RegisterTeamRequest
	6, // 7: nexus.organization.v1.OrganizationService.DeregisterTeam:input_type -> nexus.organization.v1.DeregisterTeamRequest
	1, // 8: nexus.organization.v1.OrganizationService.RegisterOrganization:output_type -> nexus.organization.v1.RegisterOrganizationResponse
	3, // 9: nexus.organization.v1.OrganizationService.DeregisterOrganization:output_type -> nexus.organization.v1.DeregisterOrganizationResponse
	5, // 10: nexus.organization.v1.OrganizationService.RegisterTeam:output_type -> nexus.organization.v1.RegisterTeamResponse
	7, // 11: nexus.organization.v1.OrganizationService.DeregisterTeam:output_type -> nexus.organization.v1.DeregisterTeamResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nexus_organization_v1_organization_proto_init() }
func file_nexus_organization_v1_organization_proto_init() {
	if File_nexus_organization_v1_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_organization_v1_organization_proto_rawDesc), len(file_nexus_organization_v1_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_organization_v1_organization_proto_goTypes,
		DependencyIndexes: file_nexus_organization_v1_organization_proto_depIdxs,
		MessageInfos:      file_nexus_organization_v1_organization_proto_msgTypes,
	}.Build()
	File_nexus_organization_v1_organization_proto = out.File
	file_nexus_organization_v1_organization_proto_goTypes = nil
	file_nexus_organization_v1_organization_proto_depIdxs = nil
}
