// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: nexus/controlplane/v1/frontend.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCollectorMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectorMetricsRequest) Reset() {
	*x = GetCollectorMetricsRequest{}
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectorMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectorMetricsRequest) ProtoMessage() {}

func (x *GetCollectorMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectorMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetCollectorMetricsRequest) Descriptor() ([]byte, []int) {
	return file_nexus_controlplane_v1_frontend_proto_rawDescGZIP(), []int{0}
}

func (x *GetCollectorMetricsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCollectorMetricsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetCollectorMetricsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetCollectorMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metrics       []*CollectorMetrics    `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectorMetricsResponse) Reset() {
	*x = GetCollectorMetricsResponse{}
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectorMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectorMetricsResponse) ProtoMessage() {}

func (x *GetCollectorMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectorMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetCollectorMetricsResponse) Descriptor() ([]byte, []int) {
	return file_nexus_controlplane_v1_frontend_proto_rawDescGZIP(), []int{1}
}

func (x *GetCollectorMetricsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCollectorMetricsResponse) GetMetrics() []*CollectorMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GetTeamSummaryRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TeamPid string                 `protobuf:"bytes,1,opt,name=team_pid,json=teamPid,proto3" json:"team_pid,omitempty"`
	// Collector statistics
	ActiveCollectorsTotal       int32 `protobuf:"varint,2,opt,name=active_collectors_total,json=activeCollectorsTotal,proto3" json:"active_collectors_total,omitempty"`
	StaleCollectorsTotal        int32 `protobuf:"varint,3,opt,name=stale_collectors_total,json=staleCollectorsTotal,proto3" json:"stale_collectors_total,omitempty"`
	UnresponsiveCollectorsTotal int32 `protobuf:"varint,4,opt,name=unresponsive_collectors_total,json=unresponsiveCollectorsTotal,proto3" json:"unresponsive_collectors_total,omitempty"`
	FlowsPerSecondTotal         int32 `protobuf:"varint,5,opt,name=flows_per_second_total,json=flowsPerSecondTotal,proto3" json:"flows_per_second_total,omitempty"`
	// Weighted average of avg_s3_put_latency_ms across collectors.
	// Formula: sum(avg_s3_put_latency_ms * s3_put_requests_total) / sum(s3_put_requests_total)
	AvgS3PutLatencyMs float64 `protobuf:"fixed64,6,opt,name=avg_s3_put_latency_ms,json=avgS3PutLatencyMs,proto3" json:"avg_s3_put_latency_ms,omitempty"`
	// Average of p99_s3_put_latency_ms across collectors.
	// Formula: sum(p99_s3_put_latency_ms) / count(collectors)
	AvgP99S3PutLatencyMs float64 `protobuf:"fixed64,7,opt,name=avg_p99_s3_put_latency_ms,json=avgP99S3PutLatencyMs,proto3" json:"avg_p99_s3_put_latency_ms,omitempty"`
	// Maximum p99_s3_put_latency_ms across collectors.
	// Formula: max(p99_s3_put_latency_ms)
	MaxP99S3PutLatencyMs float64 `protobuf:"fixed64,8,opt,name=max_p99_s3_put_latency_ms,json=maxP99S3PutLatencyMs,proto3" json:"max_p99_s3_put_latency_ms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetTeamSummaryRequest) Reset() {
	*x = GetTeamSummaryRequest{}
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamSummaryRequest) ProtoMessage() {}

func (x *GetTeamSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetTeamSummaryRequest) Descriptor() ([]byte, []int) {
	return file_nexus_controlplane_v1_frontend_proto_rawDescGZIP(), []int{2}
}

func (x *GetTeamSummaryRequest) GetTeamPid() string {
	if x != nil {
		return x.TeamPid
	}
	return ""
}

func (x *GetTeamSummaryRequest) GetActiveCollectorsTotal() int32 {
	if x != nil {
		return x.ActiveCollectorsTotal
	}
	return 0
}

func (x *GetTeamSummaryRequest) GetStaleCollectorsTotal() int32 {
	if x != nil {
		return x.StaleCollectorsTotal
	}
	return 0
}

func (x *GetTeamSummaryRequest) GetUnresponsiveCollectorsTotal() int32 {
	if x != nil {
		return x.UnresponsiveCollectorsTotal
	}
	return 0
}

func (x *GetTeamSummaryRequest) GetFlowsPerSecondTotal() int32 {
	if x != nil {
		return x.FlowsPerSecondTotal
	}
	return 0
}

func (x *GetTeamSummaryRequest) GetAvgS3PutLatencyMs() float64 {
	if x != nil {
		return x.AvgS3PutLatencyMs
	}
	return 0
}

func (x *GetTeamSummaryRequest) GetAvgP99S3PutLatencyMs() float64 {
	if x != nil {
		return x.AvgP99S3PutLatencyMs
	}
	return 0
}

func (x *GetTeamSummaryRequest) GetMaxP99S3PutLatencyMs() float64 {
	if x != nil {
		return x.MaxP99S3PutLatencyMs
	}
	return 0
}

type GetTeamSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamPid       string                 `protobuf:"bytes,1,opt,name=team_pid,json=teamPid,proto3" json:"team_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamSummaryResponse) Reset() {
	*x = GetTeamSummaryResponse{}
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamSummaryResponse) ProtoMessage() {}

func (x *GetTeamSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetTeamSummaryResponse) Descriptor() ([]byte, []int) {
	return file_nexus_controlplane_v1_frontend_proto_rawDescGZIP(), []int{3}
}

func (x *GetTeamSummaryResponse) GetTeamPid() string {
	if x != nil {
		return x.TeamPid
	}
	return ""
}

type GetQueryableFieldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetPid    string                 `protobuf:"bytes,1,opt,name=dataset_pid,json=datasetPid,proto3" json:"dataset_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryableFieldsRequest) Reset() {
	*x = GetQueryableFieldsRequest{}
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryableFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryableFieldsRequest) ProtoMessage() {}

func (x *GetQueryableFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryableFieldsRequest.ProtoReflect.Descriptor instead.
func (*GetQueryableFieldsRequest) Descriptor() ([]byte, []int) {
	return file_nexus_controlplane_v1_frontend_proto_rawDescGZIP(), []int{4}
}

func (x *GetQueryableFieldsRequest) GetDatasetPid() string {
	if x != nil {
		return x.DatasetPid
	}
	return ""
}

type GetQueryableFieldsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*Field               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryableFieldsResponse) Reset() {
	*x = GetQueryableFieldsResponse{}
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryableFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryableFieldsResponse) ProtoMessage() {}

func (x *GetQueryableFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryableFieldsResponse.ProtoReflect.Descriptor instead.
func (*GetQueryableFieldsResponse) Descriptor() ([]byte, []int) {
	return file_nexus_controlplane_v1_frontend_proto_rawDescGZIP(), []int{5}
}

func (x *GetQueryableFieldsResponse) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_controlplane_v1_frontend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_nexus_controlplane_v1_frontend_proto_rawDescGZIP(), []int{6}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_nexus_controlplane_v1_frontend_proto protoreflect.FileDescriptor

const file_nexus_controlplane_v1_frontend_proto_rawDesc = "" +
	"\n" +
	"$nexus/controlplane/v1/frontend.proto\x12\x15nexus.controlplane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)nexus/controlplane/v1/control_plane.proto\"\x9e\x01\n" +
	"\x1aGetCollectorMetricsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"p\n" +
	"\x1bGetCollectorMetricsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\ametrics\x18\x02 \x03(\v2'.nexus.controlplane.v1.CollectorMetricsR\ametrics\"\xbd\x03\n" +
	"\x15GetTeamSummaryRequest\x12\x19\n" +
	"\bteam_pid\x18\x01 \x01(\tR\ateamPid\x126\n" +
	"\x17active_collectors_total\x18\x02 \x01(\x05R\x15activeCollectorsTotal\x124\n" +
	"\x16stale_collectors_total\x18\x03 \x01(\x05R\x14staleCollectorsTotal\x12B\n" +
	"\x1dunresponsive_collectors_total\x18\x04 \x01(\x05R\x1bunresponsiveCollectorsTotal\x123\n" +
	"\x16flows_per_second_total\x18\x05 \x01(\x05R\x13flowsPerSecondTotal\x120\n" +
	"\x15avg_s3_put_latency_ms\x18\x06 \x01(\x01R\x11avgS3PutLatencyMs\x127\n" +
	"\x19avg_p99_s3_put_latency_ms\x18\a \x01(\x01R\x14avgP99S3PutLatencyMs\x127\n" +
	"\x19max_p99_s3_put_latency_ms\x18\b \x01(\x01R\x14maxP99S3PutLatencyMs\"3\n" +
	"\x16GetTeamSummaryResponse\x12\x19\n" +
	"\bteam_pid\x18\x01 \x01(\tR\ateamPid\"<\n" +
	"\x19GetQueryableFieldsRequest\x12\x1f\n" +
	"\vdataset_pid\x18\x01 \x01(\tR\n" +
	"datasetPid\"R\n" +
	"\x1aGetQueryableFieldsResponse\x124\n" +
	"\x06fields\x18\x01 \x03(\v2\x1c.nexus.controlplane.v1.FieldR\x06fields\"\x1b\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xff\x02\n" +
	"\x0fFrontendService\x12~\n" +
	"\x13GetCollectorMetrics\x121.nexus.controlplane.v1.GetCollectorMetricsRequest\x1a2.nexus.controlplane.v1.GetCollectorMetricsResponse\"\x00\x12o\n" +
	"\x0eGetTeamSummary\x12,.nexus.controlplane.v1.GetTeamSummaryRequest\x1a-.nexus.controlplane.v1.GetTeamSummaryResponse\"\x00\x12{\n" +
	"\x12GetQueryableFields\x120.nexus.controlplane.v1.GetQueryableFieldsRequest\x1a1.nexus.controlplane.v1.GetQueryableFieldsResponse\"\x00BFZDgithub.com/liquidspill/proto/go/nexus/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_nexus_controlplane_v1_frontend_proto_rawDescOnce sync.Once
	file_nexus_controlplane_v1_frontend_proto_rawDescData []byte
)

func file_nexus_controlplane_v1_frontend_proto_rawDescGZIP() []byte {
	file_nexus_controlplane_v1_frontend_proto_rawDescOnce.Do(func() {
		file_nexus_controlplane_v1_frontend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_controlplane_v1_frontend_proto_rawDesc), len(file_nexus_controlplane_v1_frontend_proto_rawDesc)))
	})
	return file_nexus_controlplane_v1_frontend_proto_rawDescData
}

var file_nexus_controlplane_v1_frontend_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_nexus_controlplane_v1_frontend_proto_goTypes = []any{
	(*GetCollectorMetricsRequest)(nil),  // 0: nexus.controlplane.v1.GetCollectorMetricsRequest
	(*GetCollectorMetricsResponse)(nil), // 1: nexus.controlplane.v1.GetCollectorMetricsResponse
	(*GetTeamSummaryRequest)(nil),       // 2: nexus.controlplane.v1.GetTeamSummaryRequest
	(*GetTeamSummaryResponse)(nil),      // 3: nexus.controlplane.v1.GetTeamSummaryResponse
	(*GetQueryableFieldsRequest)(nil),   // 4: nexus.controlplane.v1.GetQueryableFieldsRequest
	(*GetQueryableFieldsResponse)(nil),  // 5: nexus.controlplane.v1.GetQueryableFieldsResponse
	(*Field)(nil),                       // 6: nexus.controlplane.v1.Field
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
	(*CollectorMetrics)(nil),            // 8: nexus.controlplane.v1.CollectorMetrics
}
var file_nexus_controlplane_v1_frontend_proto_depIdxs = []int32{
	7, // 0: nexus.controlplane.v1.GetCollectorMetricsRequest.start_time:type_name -> google.protobuf.Timestamp
	7, // 1: nexus.controlplane.v1.GetCollectorMetricsRequest.end_time:type_name -> google.protobuf.Timestamp
	8, // 2: nexus.controlplane.v1.GetCollectorMetricsResponse.metrics:type_name -> nexus.controlplane.v1.CollectorMetrics
	6, // 3: nexus.controlplane.v1.GetQueryableFieldsResponse.fields:type_name -> nexus.controlplane.v1.Field
	0, // 4: nexus.controlplane.v1.FrontendService.GetCollectorMetrics:input_type -> nexus.controlplane.v1.GetCollectorMetricsRequest
	2, // 5: nexus.controlplane.v1.FrontendService.GetTeamSummary:input_type -> nexus.controlplane.v1.GetTeamSummaryRequest
	4, // 6: nexus.controlplane.v1.FrontendService.GetQueryableFields:input_type -> nexus.controlplane.v1.GetQueryableFieldsRequest
	1, // 7: nexus.controlplane.v1.FrontendService.GetCollectorMetrics:output_type -> nexus.controlplane.v1.GetCollectorMetricsResponse
	3, // 8: nexus.controlplane.v1.FrontendService.GetTeamSummary:output_type -> nexus.controlplane.v1.GetTeamSummaryResponse
	5, // 9: nexus.controlplane.v1.FrontendService.GetQueryableFields:output_type -> nexus.controlplane.v1.GetQueryableFieldsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nexus_controlplane_v1_frontend_proto_init() }
func file_nexus_controlplane_v1_frontend_proto_init() {
	if File_nexus_controlplane_v1_frontend_proto != nil {
		return
	}
	file_nexus_controlplane_v1_control_plane_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_controlplane_v1_frontend_proto_rawDesc), len(file_nexus_controlplane_v1_frontend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_controlplane_v1_frontend_proto_goTypes,
		DependencyIndexes: file_nexus_controlplane_v1_frontend_proto_depIdxs,
		MessageInfos:      file_nexus_controlplane_v1_frontend_proto_msgTypes,
	}.Build()
	File_nexus_controlplane_v1_frontend_proto = out.File
	file_nexus_controlplane_v1_frontend_proto_goTypes = nil
	file_nexus_controlplane_v1_frontend_proto_depIdxs = nil
}
