// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: nexus/controlplane/v1/frontend.proto

package controlplanev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/liquidspill/proto/go/nexus/controlplane/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FrontendServiceName is the fully-qualified name of the FrontendService service.
	FrontendServiceName = "nexus.controlplane.v1.FrontendService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FrontendServiceGetCollectorMetricsProcedure is the fully-qualified name of the FrontendService's
	// GetCollectorMetrics RPC.
	FrontendServiceGetCollectorMetricsProcedure = "/nexus.controlplane.v1.FrontendService/GetCollectorMetrics"
	// FrontendServiceGetQueryableFieldsProcedure is the fully-qualified name of the FrontendService's
	// GetQueryableFields RPC.
	FrontendServiceGetQueryableFieldsProcedure = "/nexus.controlplane.v1.FrontendService/GetQueryableFields"
)

// FrontendServiceClient is a client for the nexus.controlplane.v1.FrontendService service.
type FrontendServiceClient interface {
	// Get metrics from a collector
	GetCollectorMetrics(context.Context, *connect.Request[v1.GetCollectorMetricsRequest]) (*connect.Response[v1.GetCollectorMetricsResponse], error)
	// Get a list of queryable fields
	GetQueryableFields(context.Context, *connect.Request[v1.GetQueryableFieldsRequest]) (*connect.Response[v1.GetQueryableFieldsResponse], error)
}

// NewFrontendServiceClient constructs a client for the nexus.controlplane.v1.FrontendService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFrontendServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FrontendServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	frontendServiceMethods := v1.File_nexus_controlplane_v1_frontend_proto.Services().ByName("FrontendService").Methods()
	return &frontendServiceClient{
		getCollectorMetrics: connect.NewClient[v1.GetCollectorMetricsRequest, v1.GetCollectorMetricsResponse](
			httpClient,
			baseURL+FrontendServiceGetCollectorMetricsProcedure,
			connect.WithSchema(frontendServiceMethods.ByName("GetCollectorMetrics")),
			connect.WithClientOptions(opts...),
		),
		getQueryableFields: connect.NewClient[v1.GetQueryableFieldsRequest, v1.GetQueryableFieldsResponse](
			httpClient,
			baseURL+FrontendServiceGetQueryableFieldsProcedure,
			connect.WithSchema(frontendServiceMethods.ByName("GetQueryableFields")),
			connect.WithClientOptions(opts...),
		),
	}
}

// frontendServiceClient implements FrontendServiceClient.
type frontendServiceClient struct {
	getCollectorMetrics *connect.Client[v1.GetCollectorMetricsRequest, v1.GetCollectorMetricsResponse]
	getQueryableFields  *connect.Client[v1.GetQueryableFieldsRequest, v1.GetQueryableFieldsResponse]
}

// GetCollectorMetrics calls nexus.controlplane.v1.FrontendService.GetCollectorMetrics.
func (c *frontendServiceClient) GetCollectorMetrics(ctx context.Context, req *connect.Request[v1.GetCollectorMetricsRequest]) (*connect.Response[v1.GetCollectorMetricsResponse], error) {
	return c.getCollectorMetrics.CallUnary(ctx, req)
}

// GetQueryableFields calls nexus.controlplane.v1.FrontendService.GetQueryableFields.
func (c *frontendServiceClient) GetQueryableFields(ctx context.Context, req *connect.Request[v1.GetQueryableFieldsRequest]) (*connect.Response[v1.GetQueryableFieldsResponse], error) {
	return c.getQueryableFields.CallUnary(ctx, req)
}

// FrontendServiceHandler is an implementation of the nexus.controlplane.v1.FrontendService service.
type FrontendServiceHandler interface {
	// Get metrics from a collector
	GetCollectorMetrics(context.Context, *connect.Request[v1.GetCollectorMetricsRequest]) (*connect.Response[v1.GetCollectorMetricsResponse], error)
	// Get a list of queryable fields
	GetQueryableFields(context.Context, *connect.Request[v1.GetQueryableFieldsRequest]) (*connect.Response[v1.GetQueryableFieldsResponse], error)
}

// NewFrontendServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFrontendServiceHandler(svc FrontendServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	frontendServiceMethods := v1.File_nexus_controlplane_v1_frontend_proto.Services().ByName("FrontendService").Methods()
	frontendServiceGetCollectorMetricsHandler := connect.NewUnaryHandler(
		FrontendServiceGetCollectorMetricsProcedure,
		svc.GetCollectorMetrics,
		connect.WithSchema(frontendServiceMethods.ByName("GetCollectorMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	frontendServiceGetQueryableFieldsHandler := connect.NewUnaryHandler(
		FrontendServiceGetQueryableFieldsProcedure,
		svc.GetQueryableFields,
		connect.WithSchema(frontendServiceMethods.ByName("GetQueryableFields")),
		connect.WithHandlerOptions(opts...),
	)
	return "/nexus.controlplane.v1.FrontendService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FrontendServiceGetCollectorMetricsProcedure:
			frontendServiceGetCollectorMetricsHandler.ServeHTTP(w, r)
		case FrontendServiceGetQueryableFieldsProcedure:
			frontendServiceGetQueryableFieldsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFrontendServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFrontendServiceHandler struct{}

func (UnimplementedFrontendServiceHandler) GetCollectorMetrics(context.Context, *connect.Request[v1.GetCollectorMetricsRequest]) (*connect.Response[v1.GetCollectorMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("nexus.controlplane.v1.FrontendService.GetCollectorMetrics is not implemented"))
}

func (UnimplementedFrontendServiceHandler) GetQueryableFields(context.Context, *connect.Request[v1.GetQueryableFieldsRequest]) (*connect.Response[v1.GetQueryableFieldsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("nexus.controlplane.v1.FrontendService.GetQueryableFields is not implemented"))
}
