// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: fluid/controlplane/v1/controlplane.proto

package controlplanev1

import (
	v1 "github.com/liquidspill/proto/go/std/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Export        bool                   `protobuf:"varint,1,opt,name=export,proto3" json:"export,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTelemetryRequest) Reset() {
	*x = ExportTelemetryRequest{}
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTelemetryRequest) ProtoMessage() {}

func (x *ExportTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTelemetryRequest.ProtoReflect.Descriptor instead.
func (*ExportTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_fluid_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *ExportTelemetryRequest) GetExport() bool {
	if x != nil {
		return x.Export
	}
	return false
}

type ExportTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=action_at,json=actionAt,proto3" json:"action_at,omitempty"`
	Export        bool                   `protobuf:"varint,2,opt,name=export,proto3" json:"export,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTelemetryResponse) Reset() {
	*x = ExportTelemetryResponse{}
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTelemetryResponse) ProtoMessage() {}

func (x *ExportTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTelemetryResponse.ProtoReflect.Descriptor instead.
func (*ExportTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_fluid_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *ExportTelemetryResponse) GetActionAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActionAt
	}
	return nil
}

func (x *ExportTelemetryResponse) GetExport() bool {
	if x != nil {
		return x.Export
	}
	return false
}

type RegisterRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Target                `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Rule          *Rule                  `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRuleRequest) Reset() {
	*x = RegisterRuleRequest{}
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRuleRequest) ProtoMessage() {}

func (x *RegisterRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRuleRequest.ProtoReflect.Descriptor instead.
func (*RegisterRuleRequest) Descriptor() ([]byte, []int) {
	return file_fluid_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRuleRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RegisterRuleRequest) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type RegisterRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=action_at,json=actionAt,proto3" json:"action_at,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Target        *Target                `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Rule          *Rule                  `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRuleResponse) Reset() {
	*x = RegisterRuleResponse{}
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRuleResponse) ProtoMessage() {}

func (x *RegisterRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRuleResponse.ProtoReflect.Descriptor instead.
func (*RegisterRuleResponse) Descriptor() ([]byte, []int) {
	return file_fluid_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRuleResponse) GetActionAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActionAt
	}
	return nil
}

func (x *RegisterRuleResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RegisterRuleResponse) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RegisterRuleResponse) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type Target struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*Target_Devices
	//	*Target_Descriptor_
	Target        isTarget_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_fluid_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *Target) GetTarget() isTarget_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Target) GetDevices() *Devices {
	if x != nil {
		if x, ok := x.Target.(*Target_Devices); ok {
			return x.Devices
		}
	}
	return nil
}

func (x *Target) GetDescriptor_() *DeviceDescriptor {
	if x != nil {
		if x, ok := x.Target.(*Target_Descriptor_); ok {
			return x.Descriptor_
		}
	}
	return nil
}

type isTarget_Target interface {
	isTarget_Target()
}

type Target_Devices struct {
	Devices *Devices `protobuf:"bytes,1,opt,name=devices,proto3,oneof"`
}

type Target_Descriptor_ struct {
	Descriptor_ *DeviceDescriptor `protobuf:"bytes,2,opt,name=descriptor,proto3,oneof"`
}

func (*Target_Devices) isTarget_Target() {}

func (*Target_Descriptor_) isTarget_Target() {}

type Devices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceIds     []string               `protobuf:"bytes,1,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Devices) Reset() {
	*x = Devices{}
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Devices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Devices) ProtoMessage() {}

func (x *Devices) ProtoReflect() protoreflect.Message {
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Devices.ProtoReflect.Descriptor instead.
func (*Devices) Descriptor() ([]byte, []int) {
	return file_fluid_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *Devices) GetDeviceIds() []string {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

type DeviceDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Labels        []*v1.KeyValue         `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceDescriptor) Reset() {
	*x = DeviceDescriptor{}
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDescriptor) ProtoMessage() {}

func (x *DeviceDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDescriptor.ProtoReflect.Descriptor instead.
func (*DeviceDescriptor) Descriptor() ([]byte, []int) {
	return file_fluid_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceDescriptor) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *DeviceDescriptor) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceDescriptor) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DeviceDescriptor) GetLabels() []*v1.KeyValue {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_fluid_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{7}
}

type DeregisterRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRuleRequest) Reset() {
	*x = DeregisterRuleRequest{}
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRuleRequest) ProtoMessage() {}

func (x *DeregisterRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRuleRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRuleRequest) Descriptor() ([]byte, []int) {
	return file_fluid_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *DeregisterRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type DeregisterRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=action_at,json=actionAt,proto3" json:"action_at,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRuleResponse) Reset() {
	*x = DeregisterRuleResponse{}
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRuleResponse) ProtoMessage() {}

func (x *DeregisterRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fluid_controlplane_v1_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRuleResponse.ProtoReflect.Descriptor instead.
func (*DeregisterRuleResponse) Descriptor() ([]byte, []int) {
	return file_fluid_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *DeregisterRuleResponse) GetActionAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActionAt
	}
	return nil
}

func (x *DeregisterRuleResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

var File_fluid_controlplane_v1_controlplane_proto protoreflect.FileDescriptor

const file_fluid_controlplane_v1_controlplane_proto_rawDesc = "" +
	"\n" +
	"(fluid/controlplane/v1/controlplane.proto\x12\x0fcontrolplane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10std/v1/std.proto\"0\n" +
	"\x16ExportTelemetryRequest\x12\x16\n" +
	"\x06export\x18\x01 \x01(\bR\x06export\"j\n" +
	"\x17ExportTelemetryResponse\x127\n" +
	"\taction_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bactionAt\x12\x16\n" +
	"\x06export\x18\x02 \x01(\bR\x06export\"q\n" +
	"\x13RegisterRuleRequest\x12/\n" +
	"\x06target\x18\x01 \x01(\v2\x17.controlplane.v1.TargetR\x06target\x12)\n" +
	"\x04rule\x18\x02 \x01(\v2\x15.controlplane.v1.RuleR\x04rule\"\xc4\x01\n" +
	"\x14RegisterRuleResponse\x127\n" +
	"\taction_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bactionAt\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12/\n" +
	"\x06target\x18\x03 \x01(\v2\x17.controlplane.v1.TargetR\x06target\x12)\n" +
	"\x04rule\x18\x04 \x01(\v2\x15.controlplane.v1.RuleR\x04rule\"\x8d\x01\n" +
	"\x06Target\x124\n" +
	"\adevices\x18\x01 \x01(\v2\x18.controlplane.v1.DevicesH\x00R\adevices\x12C\n" +
	"\n" +
	"descriptor\x18\x02 \x01(\v2!.controlplane.v1.DeviceDescriptorH\x00R\n" +
	"descriptorB\b\n" +
	"\x06target\"(\n" +
	"\aDevices\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x01 \x03(\tR\tdeviceIds\"z\n" +
	"\x10DeviceDescriptor\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12(\n" +
	"\x06labels\x18\x04 \x03(\v2\x10.std.v1.KeyValueR\x06labels\"\x06\n" +
	"\x04Rule\"0\n" +
	"\x15DeregisterRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\"j\n" +
	"\x16DeregisterRuleResponse\x127\n" +
	"\taction_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bactionAt\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId2\xc1\x02\n" +
	"\x13ControlPlaneService\x12f\n" +
	"\x0fExportTelemetry\x12'.controlplane.v1.ExportTelemetryRequest\x1a(.controlplane.v1.ExportTelemetryResponse\"\x00\x12]\n" +
	"\fRegisterRule\x12$.controlplane.v1.RegisterRuleRequest\x1a%.controlplane.v1.RegisterRuleResponse\"\x00\x12c\n" +
	"\x0eDeregisterRule\x12&.controlplane.v1.DeregisterRuleRequest\x1a'.controlplane.v1.DeregisterRuleResponse\"\x00BFZDgithub.com/liquidspill/proto/go/fluid/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_fluid_controlplane_v1_controlplane_proto_rawDescOnce sync.Once
	file_fluid_controlplane_v1_controlplane_proto_rawDescData []byte
)

func file_fluid_controlplane_v1_controlplane_proto_rawDescGZIP() []byte {
	file_fluid_controlplane_v1_controlplane_proto_rawDescOnce.Do(func() {
		file_fluid_controlplane_v1_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fluid_controlplane_v1_controlplane_proto_rawDesc), len(file_fluid_controlplane_v1_controlplane_proto_rawDesc)))
	})
	return file_fluid_controlplane_v1_controlplane_proto_rawDescData
}

var file_fluid_controlplane_v1_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_fluid_controlplane_v1_controlplane_proto_goTypes = []any{
	(*ExportTelemetryRequest)(nil),  // 0: controlplane.v1.ExportTelemetryRequest
	(*ExportTelemetryResponse)(nil), // 1: controlplane.v1.ExportTelemetryResponse
	(*RegisterRuleRequest)(nil),     // 2: controlplane.v1.RegisterRuleRequest
	(*RegisterRuleResponse)(nil),    // 3: controlplane.v1.RegisterRuleResponse
	(*Target)(nil),                  // 4: controlplane.v1.Target
	(*Devices)(nil),                 // 5: controlplane.v1.Devices
	(*DeviceDescriptor)(nil),        // 6: controlplane.v1.DeviceDescriptor
	(*Rule)(nil),                    // 7: controlplane.v1.Rule
	(*DeregisterRuleRequest)(nil),   // 8: controlplane.v1.DeregisterRuleRequest
	(*DeregisterRuleResponse)(nil),  // 9: controlplane.v1.DeregisterRuleResponse
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
	(*v1.KeyValue)(nil),             // 11: std.v1.KeyValue
}
var file_fluid_controlplane_v1_controlplane_proto_depIdxs = []int32{
	10, // 0: controlplane.v1.ExportTelemetryResponse.action_at:type_name -> google.protobuf.Timestamp
	4,  // 1: controlplane.v1.RegisterRuleRequest.target:type_name -> controlplane.v1.Target
	7,  // 2: controlplane.v1.RegisterRuleRequest.rule:type_name -> controlplane.v1.Rule
	10, // 3: controlplane.v1.RegisterRuleResponse.action_at:type_name -> google.protobuf.Timestamp
	4,  // 4: controlplane.v1.RegisterRuleResponse.target:type_name -> controlplane.v1.Target
	7,  // 5: controlplane.v1.RegisterRuleResponse.rule:type_name -> controlplane.v1.Rule
	5,  // 6: controlplane.v1.Target.devices:type_name -> controlplane.v1.Devices
	6,  // 7: controlplane.v1.Target.descriptor:type_name -> controlplane.v1.DeviceDescriptor
	11, // 8: controlplane.v1.DeviceDescriptor.labels:type_name -> std.v1.KeyValue
	10, // 9: controlplane.v1.DeregisterRuleResponse.action_at:type_name -> google.protobuf.Timestamp
	0,  // 10: controlplane.v1.ControlPlaneService.ExportTelemetry:input_type -> controlplane.v1.ExportTelemetryRequest
	2,  // 11: controlplane.v1.ControlPlaneService.RegisterRule:input_type -> controlplane.v1.RegisterRuleRequest
	8,  // 12: controlplane.v1.ControlPlaneService.DeregisterRule:input_type -> controlplane.v1.DeregisterRuleRequest
	1,  // 13: controlplane.v1.ControlPlaneService.ExportTelemetry:output_type -> controlplane.v1.ExportTelemetryResponse
	3,  // 14: controlplane.v1.ControlPlaneService.RegisterRule:output_type -> controlplane.v1.RegisterRuleResponse
	9,  // 15: controlplane.v1.ControlPlaneService.DeregisterRule:output_type -> controlplane.v1.DeregisterRuleResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_fluid_controlplane_v1_controlplane_proto_init() }
func file_fluid_controlplane_v1_controlplane_proto_init() {
	if File_fluid_controlplane_v1_controlplane_proto != nil {
		return
	}
	file_fluid_controlplane_v1_controlplane_proto_msgTypes[4].OneofWrappers = []any{
		(*Target_Devices)(nil),
		(*Target_Descriptor_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fluid_controlplane_v1_controlplane_proto_rawDesc), len(file_fluid_controlplane_v1_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fluid_controlplane_v1_controlplane_proto_goTypes,
		DependencyIndexes: file_fluid_controlplane_v1_controlplane_proto_depIdxs,
		MessageInfos:      file_fluid_controlplane_v1_controlplane_proto_msgTypes,
	}.Build()
	File_fluid_controlplane_v1_controlplane_proto = out.File
	file_fluid_controlplane_v1_controlplane_proto_goTypes = nil
	file_fluid_controlplane_v1_controlplane_proto_depIdxs = nil
}
